Add gas meter readings support
roaldnefs/go-dsmr pull request #1
Opened 2020-02-08 14:45 UTC by legolasbo

For my pet project I also need the gas meter readings. So this PR adds support for them to your package :)

2020-02-09 16:51 UTC, roaldnefs requested changes
Thanks @legolasbo for your pull request! We you be able the change the module back to `github.com/roaldnefs/go-dsmr`?

2020-02-09 16:51 UTC, roaldnefs commented on go.mod
> +module github.com/legolasbo/go-dsmr
```suggestion
module github.com/roaldnefs/go-dsmr
```

2020-02-09 16:51 UTC, roaldnefs commented on telegram_test.go
> +	"github.com/legolasbo/go-dsmr"
```suggestion
	"github.com/roaldnefs/go-dsmr"
```

2020-02-10 07:36 UTC, legolasbo commented
Those changes didn't feel right to me either, but it seemed like the tests wouldn't pass without them. Reverted the change.

2020-02-18 12:14 UTC, legolasbo commented
Is there anything else you want me to change before merging @roaldnefs?

2020-07-25 06:46 UTC, merged

2020-07-25 06:56 UTC, roaldnefs commented
Thanks @legolasbo  for your contribution! It took a bit longer before I could test your pull request but I finally found the time.